# Introduction to Python

In [4]:
# Calculator
a = (50 + 1.45) / 12.5 # (CTRL + ENTER)
b = "hello" + " " + "world"

# print
print(a)
print(b)

4.1160000000000005
hello world

In [5]:
# Lists
x = [3, "hello", [3, 4]]
y = [1, 2, 3]
print(x + y)

[3, 'hello', [3, 4], 1, 2, 3]

In [6]:
# Flow control
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [7]:
for i in x:
    print(i)

3
hello
[3, 4]

In [8]:
i = 0
while i < 10:
    print(i)
    i += 1

0
1
2
3
4
5
6
7
8
9

In [9]:
# Functions
def plus(a, b):
    return a + b

plus(1, 2)

3

## Numpy

In [10]:
# Install library (Jupyter 7.3 or later)
%pip install numpy

Collecting numpy
  Downloading numpy-2.5.4-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Downloading numpy-2.5.4-cp314-cp314-macosx_14_0_arm64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 4.9 MB/s  0:00:01m 4.5 MB/s eta 0:00:01
Installing collected packages: numpy
Successfully installed numpy-2.5.4
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# Older versions
# import sys
# !{sys.executable} -m pip install numpy

In [11]:
# Import library
import numpy as np

In [20]:
# Numpy arrays
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

print(x)
print(y)

[3 4 5]
[4 9 7]

In [21]:
# Numpy allows mathematical operations between arrays
print(x+y)

[ 7 13 12]

In [22]:
# Different from normal lists
x = [3,4,5]
y = [4,9,7]
print(x+y)

[3, 4, 5, 4, 9, 7]

In [23]:
# 2-dimensional arrays

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a*b)

a.dtype

[[ 5 12]
 [21 32]]

dtype('int64')

In [26]:
# Documentation
np.array?

Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the same objects. See Examples for `ndarray.copy`.
    For ``False`` it raises a ``ValueError`` if a copy cannot be avoided.
    Default: ``True``.
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major).
    If object is an array the following holds.

    ===== ========= ===================================================
    order  no copy                     copy=True
    ===== ========= ===================================================
    'K'   unchanged F & C order preserved, otherwise most similar order
    'A'   unchanged F order if input is F and not C, otherwise C order
    'C'   C order   C order
    'F'   F order   F order
    ===== ========= ===================================================

    When ``copy=None`` and a copy is made for other reasons, the result is
    the same as if ``copy=True``, with some exceptions for 'A', see the
    Notes section. The default order is 'K'.
subok : bool, optional
    If True, then sub-classes will be passed-through, otherwise
    the returned array will be forced to be a base-class array (default).
ndmin : int, optional
    Specifies the minimum number of dimensions that the resulting
    array should have.  Ones will be prepended to the shape as
    needed to meet this requirement.
ndmax : int, optional
    Specifies the maximum number of dimensions to create when inferring
    shape from nested sequences. By default (ndmax=0), NumPy recurses
    through all nesting levels (up to the compile-time constant
    ``NPY_MAXDIMS``).
    Setting ``ndmax`` stops recursion at the specified depth, preserving
    deeper nested structures as objects instead of promoting them to
    higher-dimensional arrays. In this case, ``dtype=np.object_`` is required.

    .. versionadded:: 2.4.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    An array object satisfying the specified requirements.

See Also
--------
empty_like : Return an empty array with shape and type of input.
ones_like : Return an array of ones with shape and type of input.
zeros_like : Return an array of zeros with shape and type of input.
full_like : Return a new array with shape of input filled with value.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
zeros : Return a new array setting values to zero.
full : Return a new array of given shape filled with value.
copy : Return an array copy of the given object.


Notes
-----
When order is 'A' and ``object`` is an array in neither 'C' nor 'F' order,
and a copy is forced by a change in dtype, then the order of the result is
not necessarily 'C' as expected. This is likely a bug.

Examples
--------
>>> import numpy as np
>>> np.array([1, 2, 3])
array([1, 2, 3])

Upcasting:

>>> np.array([1, 2, 3.0])
array([ 1.,  2.,  3.])

More than one dimension:

>>> np.array([[1, 2], [3, 4]])
array([[1, 2],
       [3, 4]])

Minimum dimensions 2:

>>> np.array([1, 2, 3], ndmin=2)
array([[1, 2, 3]])

Type provided:

>>> np.array([1, 2, 3], dtype=np.complex128)
array([ 1.+0.j,  2.+0.j,  3.+0.j])

Data-type consisting of more than one element:

>>> x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
>>> x['a']
array([1, 3], dtype=int32)

Creating an array from sub-classes:

>>> np.array(np.asmatrix('1 2; 3 4'))
array([[1, 2],
       [3, 4]])

>>> np.array(np.asmatrix('1 2; 3 4'), subok=True)
matrix([[1, 2],
        [3, 4]])

Limiting the maximum dimensions with ``ndmax``:

>>> a = np.array([[1, 2], [3, 4]], dtype=np.object_, ndmax=2)
>>> a
array([[1, 2],
       [3, 4]], dtype=object)
>>> a.shape
(2, 2)

>>> b = np.array([[1, 2], [3, 4]], dtype=np.object_, ndmax=1)
>>> b
array([list([1, 2]), list([3, 4])], dtype=object)
>>> b.shape
(2,)
Type:      builtin_function_or_method

In [28]:
# Array dimensions
print(a.ndim)    # Number of dimensions
print(a.shape)   # Shape of the array

2
(2, 2)

In [29]:
# Reshaping arrays
a = np.array([[1, 2], [3, 4]])
print(a.reshape([1,4]))  # [rows, columns]

[[1 2 3 4]]

In [30]:
c = np.array([1, 2, 3, 4, 5, 6])
print(c.reshape(2, 3))    # Convert a 1d array to a 2x3 array

[[1 2 3]
 [4 5 6]]

## Indexing Arrays

In [31]:
A = np.array(np.arange(16)).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
# Select single element

print(A[1,2]) #[row, column]
# or
print(A[1][2])

6
6

In [38]:
# Select entire row/column
print(A[0,:])    # : selects everything

print(A[0])

print(A[:,0])

[0 1 2 3]
[0 1 2 3]
[ 0  4  8 12]

In [39]:
# Select multiple rows/columns
print(A[[1, 2],:])    # 2nd and 3rd row
print(A[:, [2,3]])    # 3rd and 4th column

[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

In [40]:
# Select a submatrix
print(A[[0,1], [0,1]]) # Doesn't work, selects individual elements [0,0] and [1,1]

[0 5]

In [ ]:
print(A[[0,1]][:,[0,1]]) # Select the rows first, then the columns

In [41]:
print(A[0:2, 0:2]) # Or with slices

[[0 1]
 [4 5]]

## Boolean indexing

In [42]:
A = [0,1,2,3,4,5,6,7,8,9]
B = [True, False, True, False, True, False, True, False, True, False]

In [43]:
A[B]  # Error - This does not work with python arrays

TypeError: list indices must be integers or slices, not list

In [44]:
# With numpy arrays, we select every element, where B == True
A = np.array(A)
print(A[B])

[0 2 4 6 8]

In [45]:
# We can use boolean indexing to select elements matching specific conditions
print(A[A > 5])
print(A[A % 2 == 0])
print(A[(A > 2) & (A < 7)])

[6 7 8 9]
[0 2 4 6 8]
[3 4 5 6]

In [46]:
# Also works with n-dimensional arrays
A = np.array(np.arange(16)).reshape((4, 4))
print(A)
rows = [True, False, True, False]
cols = [True, True, False, False]
A[rows][:,cols]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

array([[0, 1],
       [8, 9]])

In [47]:
# Select rows that sum up to more than 25
high_rows = np.sum(A, axis=1) > 25
print(high_rows)
A[high_rows]

[False False  True  True]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Pandas and Datasets

In [52]:
%pip install pandas

Collecting pandas
  Using cached pandas-3.0.6-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=2.3.3 in /Users/tadejskvorc/test/lib/python3.14/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/tadejskvorc/test/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/tadejskvorc/test/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.6-cp314-cp314-macosx_11_0_arm64.whl (10.2 MB)
Installing collected packages: pandas
Successfully installed pandas-3.0.6
Note: you may need to restart the kernel to use updated packages.

In [53]:
# In addition to Numpy arrays, we can use additional libraries to better process larger datasets
import pandas as pd

In [54]:
auto = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/mpg.csv')
auto

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

## Pandas dataframes

In [55]:
# How many examples are in a dataframe
len(auto)

398

In [58]:
# Print column names
auto.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='str')

In [59]:
# Are there missing values in the dataset
any(auto.isna())

True

In [60]:
# Count the missing values per column
auto.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [61]:
# Drop missing values
auto = auto.dropna()
print(len(auto))
print(auto.isna().sum())

392
mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [62]:
# Drop columns
auto.drop(columns="horsepower")

,mpg,cylinders,displacement,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,2720,19.4,82,usa,chevy s-10

### Indexing Pandas datasets

In [63]:
auto[1] # Error, cannot index by numbers

KeyError: 1

In [64]:
print(auto['mpg'])  # Index by column names instead

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 392, dtype: float64

In [65]:
print(auto[:3])     # Or use slices to select rows

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0

   model_year origin                       name
0          70    usa  chevrolet chevelle malibu
1          70    usa          buick skylark 320
2          70    usa         plymouth satellite

In [66]:
print(auto.loc[0,"mpg"]) # Or with .loc[row_numebr, column_name]

18.0

In [67]:
print(auto.iloc[0,0])    # Or with .iloc[row_number, column_number]

18.0

In [68]:
print(auto.loc[0:5, ["mpg", "cylinders"]])  # Can also select multiple rows and columns

    mpg  cylinders
0  18.0          8
1  15.0          8
2  18.0          8
3  16.0          8
4  17.0          8
5  15.0          8

We can use logical indexing to select specific rows

In [73]:
idx_80 = auto['model_year'] > 80
print(auto.loc[idx_80, ['name', 'model_year']])

                                  name  model_year
338                   plymouth reliant          81
339                      buick skylark          81
340             dodge aries wagon (sw)          81
341                 chevrolet citation          81
342                   plymouth reliant          81
343                     toyota starlet          81
344                     plymouth champ          81
345                   honda civic 1300          81
346                             subaru          81
347                     datsun 210 mpg          81
348                      toyota tercel          81
349                        mazda glc 4          81
350                 plymouth horizon 4          81
351                     ford escort 4w          81
352                     ford escort 2h          81
353                   volkswagen jetta          81
355                      honda prelude          81
356                     toyota corolla          81
357                       datsun 200sx          81
358                          mazda 626          81
359          peugeot 505s turbo diesel          81
360                       volvo diesel          81
361                    toyota cressida          81
362                  datsun 810 maxima          81
363                      buick century          81
364              oldsmobile cutlass ls          81
365                    ford granada gl          81
366             chrysler lebaron salon          81
367                 chevrolet cavalier          82
368           chevrolet cavalier wagon          82
369          chevrolet cavalier 2-door          82
370         pontiac j2000 se hatchback          82
371                     dodge aries se          82
372                    pontiac phoenix          82
373               ford fairmont futura          82
375                volkswagen rabbit l          82
376                 mazda glc custom l          82
377                   mazda glc custom          82
378             plymouth horizon miser          82
379                     mercury lynx l          82
380                   nissan stanza xe          82
381                       honda accord          82
382                     toyota corolla          82
383                        honda civic          82
384                 honda civic (auto)          82
385                      datsun 310 gx          82
386              buick century limited          82
387  oldsmobile cutlass ciera (diesel)          82
388         chrysler lebaron medallion          82
389                     ford granada l          82
390                   toyota celica gt          82
391                  dodge charger 2.2          82
392                   chevrolet camaro          82
393                    ford mustang gl          82
394                          vw pickup          82
395                      dodge rampage          82
396                        ford ranger          82
397                         chevy s-10          82

In [71]:
# Or in one line
print(auto.loc[auto['model_year'] > 80, ['name', 'model_year']])

                                  name  model_year
338                   plymouth reliant          81
339                      buick skylark          81
340             dodge aries wagon (sw)          81
341                 chevrolet citation          81
342                   plymouth reliant          81
343                     toyota starlet          81
344                     plymouth champ          81
345                   honda civic 1300          81
346                             subaru          81
347                     datsun 210 mpg          81
348                      toyota tercel          81
349                        mazda glc 4          81
350                 plymouth horizon 4          81
351                     ford escort 4w          81
352                     ford escort 2h          81
353                   volkswagen jetta          81
355                      honda prelude          81
356                     toyota corolla          81
357                       datsun 200sx          81
358                          mazda 626          81
359          peugeot 505s turbo diesel          81
360                       volvo diesel          81
361                    toyota cressida          81
362                  datsun 810 maxima          81
363                      buick century          81
364              oldsmobile cutlass ls          81
365                    ford granada gl          81
366             chrysler lebaron salon          81
367                 chevrolet cavalier          82
368           chevrolet cavalier wagon          82
369          chevrolet cavalier 2-door          82
370         pontiac j2000 se hatchback          82
371                     dodge aries se          82
372                    pontiac phoenix          82
373               ford fairmont futura          82
375                volkswagen rabbit l          82
376                 mazda glc custom l          82
377                   mazda glc custom          82
378             plymouth horizon miser          82
379                     mercury lynx l          82
380                   nissan stanza xe          82
381                       honda accord          82
382                     toyota corolla          82
383                        honda civic          82
384                 honda civic (auto)          82
385                      datsun 310 gx          82
386              buick century limited          82
387  oldsmobile cutlass ciera (diesel)          82
388         chrysler lebaron medallion          82
389                     ford granada l          82
390                   toyota celica gt          82
391                  dodge charger 2.2          82
392                   chevrolet camaro          82
393                    ford mustang gl          82
394                          vw pickup          82
395                      dodge rampage          82
396                        ford ranger          82
397                         chevy s-10          82

## Adding values

In [74]:
# Create new column
auto['Horsepower / Weight'] = auto['horsepower'] / auto['weight']
auto

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,Horsepower / Weight
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu,0.037100
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320,0.044679
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite,0.043655
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst,0.043694
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino,0.040591
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl,0.030824
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup,0.024413
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage,0.036601
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger,0.030095
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10,0.030147

In [ ]:
# Create a new empty row as a pd.Series
new_row = pd.Series([None]*10, index=['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
                                      'acceleration', 'model_year', 'origin', 'name', 'Horsepower / Weight'])

# Concatenate the new empty row with the original DataFrame
result = pd.concat([auto, new_row.to_frame().T], ignore_index=True)
result

## Additional functions

In [ ]:
# Merge datasets
pd.concat([auto, auto])

# This can also be used to add new rows - simply create a new dataframe and concat it to the original

In [ ]:
# Save dataset
auto.to_csv('./is_lab_1_dataset.txt', index=False)